version: '3'

services:

  weather_service:
    container_name: weather_service
    build: ./weatherService
    command: npm start
    volumes:
      - "./weatherService:/usr/weatherService"
    ports:
      - 3001:3001
    env_file:
      - keys.env
